// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvYwe_oKE9sb1cL-4Ty9q0gCF50zlHL-M',
    appId: '1:150924839535:web:3517517dbc0a1db5c39b9a',
    messagingSenderId: '150924839535',
    projectId: 'messaging-app-b1e91',
    authDomain: 'messaging-app-b1e91.firebaseapp.com',
    storageBucket: 'messaging-app-b1e91.appspot.com',
    measurementId: 'G-Y4G4Q9LZGC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7knfCkNUQPb_lA9QKRCqGOdcOXEwY0YA',
    appId: '1:150924839535:android:2701520f0db8c490c39b9a',
    messagingSenderId: '150924839535',
    projectId: 'messaging-app-b1e91',
    storageBucket: 'messaging-app-b1e91.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxT8tnsK4w5UY2fs08F2wZ6NNicj306Qs',
    appId: '1:150924839535:ios:725f279e8adbe54bc39b9a',
    messagingSenderId: '150924839535',
    projectId: 'messaging-app-b1e91',
    storageBucket: 'messaging-app-b1e91.appspot.com',
    iosBundleId: 'com.example.messagingapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxT8tnsK4w5UY2fs08F2wZ6NNicj306Qs',
    appId: '1:150924839535:ios:ab1717670bb5aa8ac39b9a',
    messagingSenderId: '150924839535',
    projectId: 'messaging-app-b1e91',
    storageBucket: 'messaging-app-b1e91.appspot.com',
    iosBundleId: 'com.example.messagingapp.RunnerTests',
  );
}
